export const CardDatas = [
    {
        productId: "easy-rider-leather-1",
        slug: "easy-rider-leather-unisex-sneakers",
        name:"Easy Rider Leather Unisex Sneakers",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Classic leather sneakers with retro design",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers2.jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 0,
        gender: "unisex-adults"
    },
    {
        productId: "blktop-rider-neo-vintage-1",
        slug: "blktop-rider-neo-vintage-unisex-sneakers",
        name:"Blktop Rider Neo Vintage Unisex Sneakers",
        price:"₹9,499",
        description:"Vintage-inspired design with modern comfort",
        img:"/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers.jpeg",
        basePrice: 9499,
        discountType: null,
        discountValue: 0,
        stock: 15,
        gender: "unisex-adults"
    },
    {
        productId: "blktop-rider-neo-vintage-2",
        slug: "blktop-rider-neo-vintage-unisex-sneakers-black",
        name:"Blktop Rider Neo Vintage - Black Edition",
        price:"₹9,499",
        offerPrice:"₹8,499",
        description:"Premium black colorway with vintage appeal",
        img:"/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers (1).jpeg",
        basePrice: 9499,
        discountType: "PERCENT",
        discountValue: 11,
        stock: 12,
        gender: "unisex-adults"
    },
    {
        productId: "easy-rider-mesh-1",
        slug: "easy-rider-mesh-unisex-sneakers",
        name:"Easy Rider Mesh Unisex Sneakers",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Breathable mesh upper for all-day comfort",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers.jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 18,
        gender: "unisex-adults"
    },
    {
        productId: "easy-rider-mesh-2",
        slug: "easy-rider-mesh-unisex-sneakers-white",
        name:"Easy Rider Mesh - White & Black",
        price:"₹8,999",
        offerPrice:"₹7,499",
        description:"Classic white and black color combination",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (1).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 17,
        stock: 20,
        gender: "female"
    },
    {
        productId: "blktop-rider-neo-vintage-3",
        slug: "blktop-rider-neo-vintage-unisex-sneakers-gray",
        name:"Blktop Rider Neo Vintage - Gray",
        price:"₹9,499",
        description:"Sophisticated gray colorway",
        img:"/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers (2).jpeg",
        basePrice: 9499,
        discountType: null,
        discountValue: 0,
        stock: 0,
        gender: "unisex-adults"
    },
    {
        productId: "magmax-nitro-running-1",
        slug: "magmax-nitro-mens-running-shoes",
        name:"MagMax NITRO Men's Running Shoes",
        price:"₹12,999",
        offerPrice:"₹10,999",
        description:"Advanced NITRO technology for superior cushioning",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes.jpeg",
        basePrice: 12999,
        discountType: "PERCENT",
        discountValue: 15,
        stock: 25,
        gender: "male"
    },
    {
        productId: "magmax-nitro-running-2",
        slug: "magmax-nitro-mens-running-shoes-blue",
        name:"MagMax NITRO - Blue & White",
        price:"₹12,999",
        offerPrice:"₹11,499",
        description:"Dynamic blue colorway with NITRO foam",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (1).jpeg",
        basePrice: 12999,
        discountType: "PERCENT",
        discountValue: 12,
        stock: 22,
        gender: "male"
    },
    {
        productId: "easy-rider-mesh-3",
        slug: "easy-rider-mesh-unisex-sneakers-gray",
        name:"Easy Rider Mesh - Gray & White",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Versatile gray mesh design",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (2).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 16,
        gender: "female"
    },
    {
        productId: "easy-rider-leather-2",
        slug: "easy-rider-leather-unisex-sneakers-classic",
        name:"Easy Rider Leather - Classic Brown",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Timeless brown leather finish",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers2.jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 14,
        gender: "unisex-adults"
    },
    {
        productId: "magmax-nitro-running-3",
        slug: "magmax-nitro-mens-running-shoes-black",
        name:"MagMax NITRO - Black Edition",
        price:"₹12,999",
        offerPrice:"₹10,999",
        description:"Sleek black design with maximum performance",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (6).jpeg",
        basePrice: 12999,
        discountType: "PERCENT",
        discountValue: 15,
        stock: 19,
        gender: "male"
    },
    {
        productId: "easy-rider-mesh-4",
        slug: "easy-rider-mesh-unisex-sneakers-navy",
        name:"Easy Rider Mesh - Navy Blue",
        price:"₹8,999",
        offerPrice:"₹7,499",
        description:"Stylish navy blue mesh sneakers",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (3).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 17,
        stock: 17,
        gender: "unisex-adults"
    },
    {
        productId: "magmax-nitro-running-4",
        slug: "magmax-nitro-mens-running-shoes-red",
        name:"MagMax NITRO - Red & Black",
        price:"₹12,999",
        offerPrice:"₹11,499",
        description:"Bold red accents for high visibility",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (2).jpeg",
        basePrice: 12999,
        discountType: "PERCENT",
        discountValue: 12,
        stock: 21,
        gender: "male"
    },
    {
        productId: "easy-rider-leather-3",
        slug: "easy-rider-leather-unisex-sneakers-black",
        name:"Easy Rider Leather - Black Premium",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Premium black leather with retro styling",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (3).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 13,
        gender: "unisex-adults"
    },
    {
        productId: "magmax-nitro-running-5",
        slug: "magmax-nitro-mens-running-shoes-gray",
        name:"MagMax NITRO - Gray & Orange",
        price:"₹12,999",
        offerPrice:"₹11,499",
        description:"Modern gray with vibrant orange details",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (3).jpeg",
        basePrice: 12999,
        discountType: "PERCENT",
        discountValue: 12,
        stock: 23,
        gender: "male"
    },
    {
        productId: "easy-rider-leather-4",
        slug: "easy-rider-leather-unisex-sneakers-white",
        name:"Easy Rider Leather - White Classic",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Clean white leather design",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (4).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 0,
        gender: "female"
    },
    {
        productId: "magmax-nitro-running-6",
        slug: "magmax-nitro-mens-running-shoes-white",
        name:"MagMax NITRO - White & Blue",
        price:"₹12,999",
        offerPrice:"₹10,999",
        description:"Fresh white with blue accents",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (4).jpeg",
        basePrice: 12999,
        discountType: "PERCENT",
        discountValue: 15,
        stock: 24,
        gender: "male"
    },
    {
        productId: "easy-rider-mesh-5",
        slug: "easy-rider-mesh-unisex-sneakers-red",
        name:"Easy Rider Mesh - Red & White",
        price:"₹8,999",
        offerPrice:"₹7,499",
        description:"Bold red mesh with white sole",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (4).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 17,
        stock: 15,
        gender: "unisex-adults"
    },
    {
        productId: "magmax-nitro-running-7",
        slug: "magmax-nitro-mens-running-shoes-green",
        name:"MagMax NITRO - Green & Black",
        price:"₹12,999",
        offerPrice:"₹11,499",
        description:"Eco-friendly green with black details",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (5).jpeg",
        basePrice: 12999,
        discountType: "PERCENT",
        discountValue: 12,
        stock: 20,
        gender: "male"
    },
    {
        productId: "easy-rider-leather-5",
        slug: "easy-rider-leather-unisex-sneakers-tan",
        name:"Easy Rider Leather - Tan Brown",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Rich tan brown leather finish",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (5).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 9,
        gender: "unisex-adults"
    },
    {
        productId: "magmax-nitro-running-8",
        slug: "magmax-nitro-mens-running-shoes-purple",
        name:"MagMax NITRO - Purple & White",
        price:"₹12,999",
        offerPrice:"₹11,499",
        description:"Unique purple colorway with white",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (7).jpeg",
        basePrice: 12999,
        discountType: "PERCENT",
        discountValue: 12,
        stock: 18,
        gender: "male"
    },
    {
        productId: "easy-rider-leather-6",
        slug: "easy-rider-leather-unisex-sneakers-navy",
        name:"Easy Rider Leather - Navy Blue",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Sophisticated navy blue leather",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (6).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 12,
        gender: "female"
    },
    {
        productId: "magmax-nitro-running-9",
        slug: "magmax-nitro-mens-running-shoes-yellow",
        name:"MagMax NITRO - Yellow & Black",
        price:"₹12,999",
        offerPrice:"₹11,499",
        description:"Vibrant yellow with black contrast",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (8).jpeg",
        basePrice: 12999,
        discountType: "PERCENT",
        discountValue: 12,
        stock: 16,
        gender: "male"
    },
    {
        productId: "easy-rider-leather-7",
        slug: "easy-rider-leather-unisex-sneakers-gray",
        name:"Easy Rider Leather - Gray Premium",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Elegant gray leather design",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (7).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 10,
        gender: "unisex-adults"
    },
    {
        productId: "easy-rider-leather-8",
        slug: "easy-rider-leather-unisex-sneakers-red",
        name:"Easy Rider Leather - Red Classic",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Bold red leather sneakers",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (8).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 0,
        gender: "unisex-adults"
    },
    {
        productId: "softride-pro-coast-1",
        slug: "softride-pro-coast-res-unisex-running-shoes",
        name:"Softride Pro Coast Res Unisex Running Shoes",
        price:"₹9,999",
        offerPrice:"₹8,499",
        description:"Coastal-inspired design with softride technology",
        img:"/Images/Products/cards/Softride-Pro-Coast-Res-Unisex-Running-Shoes (2).jpeg",
        basePrice: 9999,
        discountType: "PERCENT",
        discountValue: 15,
        stock: 26,
        gender: "unisex-adults"
    },
    {
        productId: "softride-pro-coast-2",
        slug: "softride-pro-coast-res-unisex-running-shoes-blue",
        name:"Softride Pro Coast - Ocean Blue",
        price:"₹9,999",
        offerPrice:"₹8,499",
        description:"Ocean blue colorway for coastal runs",
        img:"/Images/Products/cards/Softride-Pro-Coast-Res-Unisex-Running-Shoes (3).jpeg",
        basePrice: 9999,
        discountType: "PERCENT",
        discountValue: 15,
        stock: 28,
        gender: "female"
    },
    {
        productId: "rs-x-efekt-1",
        slug: "rs-x-efekt-unisex-sneakers",
        name:"RS-X Efekt Unisex Sneakers",
        price:"₹10,999",
        offerPrice:"₹8,799",
        description:"Bold design with retro-futuristic style",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers2.jpeg",
        basePrice: 10999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 30,
        gender: "unisex-adults"
    },
    {
        productId: "rs-x-efekt-2",
        slug: "rs-x-efekt-unisex-sneakers-black",
        name:"RS-X Efekt - Black & White",
        price:"₹10,999",
        offerPrice:"₹9,499",
        description:"Classic black and white colorway",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (3).jpeg",
        basePrice: 10999,
        discountType: "PERCENT",
        discountValue: 14,
        stock: 25,
        gender: "male"
    },
    {
        productId: "rs-x-efekt-3",
        slug: "rs-x-efekt-unisex-sneakers-pink",
        name:"RS-X Efekt - Pink & Gray",
        price:"₹10,999",
        offerPrice:"₹9,499",
        description:"Vibrant pink with gray accents",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (1).jpeg",
        basePrice: 10999,
        discountType: "PERCENT",
        discountValue: 14,
        stock: 22,
        gender: "female"
    },
    {
        productId: "suede-classic-1",
        slug: "suede-classic-unisex-sneakers",
        name:"Suede Classic Unisex Sneakers",
        price:"₹7,499",
        offerPrice:"₹5,999",
        description:"Iconic suede upper with timeless design",
        img:"/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers.jpeg",
        basePrice: 7499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 35,
        gender: "unisex-adults"
    },
    {
        productId: "suede-classic-2",
        slug: "suede-classic-unisex-sneakers-white",
        name:"Suede Classic - White",
        price:"₹7,499",
        offerPrice:"₹6,499",
        description:"Clean white suede finish",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (4).jpeg",
        basePrice: 7499,
        discountType: "PERCENT",
        discountValue: 13,
        stock: 28,
        gender: "female"
    },
    {
        productId: "suede-classic-3",
        slug: "suede-classic-unisex-sneakers-black",
        name:"Suede Classic - Black",
        price:"₹7,499",
        offerPrice:"₹6,499",
        description:"Premium black suede",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (3).jpeg",
        basePrice: 7499,
        discountType: "PERCENT",
        discountValue: 13,
        stock: 32,
        gender: "male"
    },
    {
        productId: "velocity-nitro-1",
        slug: "velocity-nitro-mens-running-shoes",
        name:"Velocity NITRO Men's Running Shoes",
        price:"₹11,999",
        offerPrice:"₹9,599",
        description:"Lightweight performance running shoes",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes.jpeg",
        basePrice: 11999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 27,
        gender: "male"
    },
    {
        productId: "velocity-nitro-2",
        slug: "velocity-nitro-mens-running-shoes-blue",
        name:"Velocity NITRO - Blue & Orange",
        price:"₹11,999",
        offerPrice:"₹10,199",
        description:"Dynamic blue with orange highlights",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (1).jpeg",
        basePrice: 11999,
        discountType: "PERCENT",
        discountValue: 15,
        stock: 24,
        gender: "male"
    },
    {
        productId: "carina-2-0-1",
        slug: "carina-2-0-womens-sneakers",
        name:"Carina 2.0 Women's Sneakers",
        price:"₹8,499",
        offerPrice:"₹6,799",
        description:"Stylish women's sneakers with modern design",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers.jpeg",
        basePrice: 8499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 29,
        gender: "female"
    },
    {
        productId: "carina-2-0-2",
        slug: "carina-2-0-womens-sneakers-white",
        name:"Carina 2.0 - White & Pink",
        price:"₹8,499",
        offerPrice:"₹7,199",
        description:"Elegant white with pink accents",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (1).jpeg",
        basePrice: 8499,
        discountType: "PERCENT",
        discountValue: 15,
        stock: 26,
        gender: "female"
    },
    {
        productId: "thunder-spectra-1",
        slug: "thunder-spectra-unisex-sneakers",
        name:"Thunder Spectra Unisex Sneakers",
        price:"₹9,999",
        offerPrice:"₹7,999",
        description:"Bold chunky design with retro appeal",
        img:"/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers (1).jpeg",
        basePrice: 9999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 31,
        gender: "unisex-adults"
    },
    {
        productId: "thunder-spectra-2",
        slug: "thunder-spectra-unisex-sneakers-black",
        name:"Thunder Spectra - Black & Yellow",
        price:"₹9,999",
        offerPrice:"₹8,499",
        description:"Striking black with yellow details",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (8).jpeg",
        basePrice: 9999,
        discountType: "PERCENT",
        discountValue: 15,
        stock: 23,
        gender: "unisex-adults"
    },
    {
        productId: "basket-classic-1",
        slug: "basket-classic-unisex-sneakers",
        name:"Basket Classic Unisex Sneakers",
        price:"₹6,999",
        offerPrice:"₹5,599",
        description:"Classic basketball-inspired design",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers2.jpeg",
        basePrice: 6999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 33,
        gender: "unisex-adults"
    },
    {
        productId: "basket-classic-2",
        slug: "basket-classic-unisex-sneakers-red",
        name:"Basket Classic - Red & White",
        price:"₹6,999",
        offerPrice:"₹6,299",
        description:"Classic red and white colorway",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (8).jpeg",
        basePrice: 6999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 30,
        gender: "male"
    },
    {
        productId: "future-rider-1",
        slug: "future-rider-unisex-sneakers",
        name:"Future Rider Unisex Sneakers",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Futuristic design with retro elements",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (2).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 27,
        gender: "unisex-adults"
    },
    {
        productId: "future-rider-2",
        slug: "future-rider-unisex-sneakers-gray",
        name:"Future Rider - Gray & Neon",
        price:"₹8,999",
        offerPrice:"₹7,649",
        description:"Modern gray with neon accents",
        img:"/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers (2).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 15,
        stock: 25,
        gender: "unisex-adults"
    },
    {
        productId: "cali-sport-1",
        slug: "cali-sport-womens-sneakers",
        name:"Cali Sport Women's Sneakers",
        price:"₹7,999",
        offerPrice:"₹6,399",
        description:"California-inspired casual sneakers",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (3).jpeg",
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 28,
        gender: "female"
    },
    {
        productId: "cali-sport-2",
        slug: "cali-sport-womens-sneakers-beige",
        name:"Cali Sport - Beige & White",
        price:"₹7,999",
        offerPrice:"₹6,799",
        description:"Sophisticated beige colorway",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (4).jpeg",
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 15,
        stock: 24,
        gender: "female"
    },
    {
        productId: "smash-v2-1",
        slug: "smash-v2-unisex-sneakers",
        name:"Smash V2 Unisex Sneakers",
        price:"₹6,499",
        offerPrice:"₹5,199",
        description:"Versatile everyday sneakers",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (5).jpeg",
        basePrice: 6499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 36,
        gender: "unisex-adults"
    },
    {
        productId: "smash-v2-2",
        slug: "smash-v2-unisex-sneakers-navy",
        name:"Smash V2 - Navy & White",
        price:"₹6,499",
        offerPrice:"₹5,849",
        description:"Classic navy and white design",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (6).jpeg",
        basePrice: 6499,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 34,
        gender: "unisex-adults"
    },
    {
        productId: "leadcat-1",
        slug: "leadcat-unisex-sneakers",
        name:"Leadcat Unisex Sneakers",
        price:"₹5,999",
        offerPrice:"₹4,799",
        description:"Minimalist design with comfort focus",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (7).jpeg",
        basePrice: 5999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 38,
        gender: "unisex-adults"
    },
    {
        productId: "leadcat-2",
        slug: "leadcat-unisex-sneakers-white",
        name:"Leadcat - White",
        price:"₹5,999",
        offerPrice:"₹5,399",
        description:"Clean white minimalist design",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (4).jpeg",
        basePrice: 5999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 35,
        gender: "female"
    },
    {
        productId: "clyde-all-pro-1",
        slug: "clyde-all-pro-unisex-sneakers",
        name:"Clyde All-Pro Unisex Sneakers",
        price:"₹9,499",
        offerPrice:"₹7,599",
        description:"Performance-focused basketball sneakers",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (2).jpeg",
        basePrice: 9499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 22,
        gender: "male"
    },
    {
        productId: "clyde-all-pro-2",
        slug: "clyde-all-pro-unisex-sneakers-black",
        name:"Clyde All-Pro - Black & Gold",
        price:"₹9,499",
        offerPrice:"₹8,549",
        description:"Premium black with gold accents",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (6).jpeg",
        basePrice: 9499,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 20,
        gender: "male"
    },
    {
        productId: "mayze-1",
        slug: "mayze-womens-sneakers",
        name:"Mayze Women's Sneakers",
        price:"₹7,499",
        offerPrice:"₹5,999",
        description:"Fashion-forward women's sneakers",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (4).jpeg",
        basePrice: 7499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 31,
        gender: "female"
    },
    {
        productId: "mayze-2",
        slug: "mayze-womens-sneakers-rose",
        name:"Mayze - Rose Gold",
        price:"₹7,499",
        offerPrice:"₹6,749",
        description:"Elegant rose gold colorway",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (1).jpeg",
        basePrice: 7499,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 28,
        gender: "female"
    },
    {
        productId: "rs-x3-1",
        slug: "rs-x3-unisex-sneakers",
        name:"RS-X3 Unisex Sneakers",
        price:"₹10,499",
        offerPrice:"₹8,399",
        description:"Advanced RS-X series with modern tech",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (3).jpeg",
        basePrice: 10499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 26,
        gender: "unisex-adults"
    },
    {
        productId: "rs-x3-2",
        slug: "rs-x3-unisex-sneakers-multicolor",
        name:"RS-X3 - Multicolor",
        price:"₹10,499",
        offerPrice:"₹9,449",
        description:"Bold multicolor design",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (4).jpeg",
        basePrice: 10499,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 23,
        gender: "unisex-adults"
    },
    {
        productId: "speedcat-1",
        slug: "speedcat-unisex-sneakers",
        name:"Speedcat Unisex Sneakers",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Racing-inspired design",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (5).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 29,
        gender: "male"
    },
    {
        productId: "speedcat-2",
        slug: "speedcat-unisex-sneakers-red",
        name:"Speedcat - Red & Black",
        price:"₹8,999",
        offerPrice:"₹8,099",
        description:"Racing red with black details",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (2).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 27,
        gender: "male"
    },
    {
        productId: "platform-trace-1",
        slug: "platform-trace-womens-sneakers",
        name:"Platform Trace Women's Sneakers",
        price:"₹8,499",
        offerPrice:"₹6,799",
        description:"Elevated platform design",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (8).jpeg",
        basePrice: 8499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 32,
        gender: "female"
    },
    {
        productId: "platform-trace-2",
        slug: "platform-trace-womens-sneakers-white",
        name:"Platform Trace - White & Silver",
        price:"₹8,499",
        offerPrice:"₹7,649",
        description:"Elegant white with silver accents",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (4).jpeg",
        basePrice: 8499,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 30,
        gender: "female"
    },
    {
        productId: "cell-venom-1",
        slug: "cell-venom-unisex-sneakers",
        name:"Cell Venom Unisex Sneakers",
        price:"₹9,999",
        offerPrice:"₹7,999",
        description:"Aggressive design with cell technology",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (7).jpeg",
        basePrice: 9999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 24,
        gender: "unisex-adults"
    },
    {
        productId: "cell-venom-2",
        slug: "cell-venom-unisex-sneakers-green",
        name:"Cell Venom - Green & Black",
        price:"₹9,999",
        offerPrice:"₹8,999",
        description:"Bold green with black contrast",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (5).jpeg",
        basePrice: 9999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 21,
        gender: "male"
    },
    {
        productId: "kids-rs-x-1",
        slug: "kids-rs-x-sneakers",
        name:"Kids RS-X Sneakers",
        price:"₹5,999",
        offerPrice:"₹4,799",
        description:"Fun kids sneakers with bold design",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers2.jpeg",
        basePrice: 5999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 40,
        gender: "boys"
    },
    {
        productId: "kids-rs-x-2",
        slug: "kids-rs-x-sneakers-blue",
        name:"Kids RS-X - Blue & Yellow",
        price:"₹5,999",
        offerPrice:"₹5,399",
        description:"Vibrant blue and yellow for kids",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers.jpeg",
        basePrice: 5999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 38,
        gender: "boys"
    },
    {
        productId: "kids-platform-1",
        slug: "kids-platform-sneakers",
        name:"Kids Platform Sneakers",
        price:"₹4,999",
        offerPrice:"₹3,999",
        description:"Comfortable platform sneakers for kids",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (3).jpeg",
        basePrice: 4999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 42,
        gender: "unisex-kids"
    },
    {
        productId: "kids-platform-2",
        slug: "kids-platform-sneakers-pink",
        name:"Kids Platform - Pink & Purple",
        price:"₹4,999",
        offerPrice:"₹4,499",
        description:"Cute pink and purple design",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (1).jpeg",
        basePrice: 4999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 40,
        gender: "unisex-kids"
    },
    {
        productId: "rebound-joey-1",
        slug: "rebound-joey-unisex-sneakers",
        name:"Rebound Joey Unisex Sneakers",
        price:"₹7,999",
        offerPrice:"₹6,399",
        description:"Basketball-inspired casual sneakers",
        img:"/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers.jpeg",
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 33,
        gender: "unisex-adults"
    },
    {
        productId: "rebound-joey-2",
        slug: "rebound-joey-unisex-sneakers-black",
        name:"Rebound Joey - Black & White",
        price:"₹7,999",
        offerPrice:"₹7,199",
        description:"Classic black and white colorway",
        img:"/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers (1).jpeg",
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 31,
        gender: "male"
    },
    {
        productId: "tazon-6-1",
        slug: "tazon-6-mens-running-shoes",
        name:"Tazon 6 Men's Running Shoes",
        price:"₹6,999",
        offerPrice:"₹5,599",
        description:"Lightweight running shoes for men",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes.jpeg",
        basePrice: 6999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 37,
        gender: "male"
    },
    {
        productId: "tazon-6-2",
        slug: "tazon-6-mens-running-shoes-gray",
        name:"Tazon 6 - Gray & Blue",
        price:"₹6,999",
        offerPrice:"₹6,299",
        description:"Modern gray with blue accents",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (1).jpeg",
        basePrice: 6999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 35,
        gender: "male"
    },
    {
        productId: "ignite-dual-1",
        slug: "ignite-dual-womens-running-shoes",
        name:"Ignite Dual Women's Running Shoes",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Dual-density cushioning for women",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (2).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 34,
        gender: "female"
    },
    {
        productId: "ignite-dual-2",
        slug: "ignite-dual-womens-running-shoes-purple",
        name:"Ignite Dual - Purple & Pink",
        price:"₹8,999",
        offerPrice:"₹8,099",
        description:"Beautiful purple and pink gradient",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (3).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 32,
        gender: "female"
    },
    {
        productId: "stunner-1",
        slug: "stunner-unisex-sneakers",
        name:"Stunner Unisex Sneakers",
        price:"₹5,499",
        offerPrice:"₹4,399",
        description:"Affordable everyday sneakers",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (5).jpeg",
        basePrice: 5499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 45,
        gender: "unisex-adults"
    },
    {
        productId: "stunner-2",
        slug: "stunner-unisex-sneakers-black",
        name:"Stunner - Black",
        price:"₹5,499",
        offerPrice:"₹4,949",
        description:"Classic black affordable sneakers",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (3).jpeg",
        basePrice: 5499,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 43,
        gender: "unisex-adults"
    },
    {
        productId: "fierce-1",
        slug: "fierce-womens-running-shoes",
        name:"Fierce Women's Running Shoes",
        price:"₹7,499",
        offerPrice:"₹5,999",
        description:"Performance running shoes for women",
        img:"/Images/Products/cards/Softride-Pro-Coast-Res-Unisex-Running-Shoes (2).jpeg",
        basePrice: 7499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 36,
        gender: "female"
    },
    {
        productId: "fierce-2",
        slug: "fierce-womens-running-shoes-teal",
        name:"Fierce - Teal & White",
        price:"₹7,499",
        offerPrice:"₹6,749",
        description:"Fresh teal colorway",
        img:"/Images/Products/cards/Softride-Pro-Coast-Res-Unisex-Running-Shoes (3).jpeg",
        basePrice: 7499,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 34,
        gender: "female"
    },
    {
        productId: "caven-1",
        slug: "caven-unisex-sneakers",
        name:"Caven Unisex Sneakers",
        price:"₹6,999",
        offerPrice:"₹5,599",
        description:"Urban street style sneakers",
        img:"/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers (2).jpeg",
        basePrice: 6999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 39,
        gender: "unisex-adults"
    },
    {
        productId: "caven-2",
        slug: "caven-unisex-sneakers-olive",
        name:"Caven - Olive & Black",
        price:"₹6,999",
        offerPrice:"₹6,299",
        description:"Trendy olive green design",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (6).jpeg",
        basePrice: 6999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 37,
        gender: "unisex-adults"
    },
    {
        productId: "tsugi-shinsei-1",
        slug: "tsugi-shinsei-unisex-sneakers",
        name:"Tsugi Shinsei Unisex Sneakers",
        price:"₹9,999",
        offerPrice:"₹7,999",
        description:"Japanese-inspired design",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (3).jpeg",
        basePrice: 9999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 25,
        gender: "unisex-adults"
    },
    {
        productId: "tsugi-shinsei-2",
        slug: "tsugi-shinsei-unisex-sneakers-beige",
        name:"Tsugi Shinsei - Beige & Brown",
        price:"₹9,999",
        offerPrice:"₹8,999",
        description:"Elegant beige and brown tones",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (5).jpeg",
        basePrice: 9999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 23,
        gender: "unisex-adults"
    },
    {
        productId: "disc-blaze-1",
        slug: "disc-blaze-unisex-sneakers",
        name:"Disc Blaze Unisex Sneakers",
        price:"₹8,499",
        offerPrice:"₹6,799",
        description:"90s retro design with disc system",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (4).jpeg",
        basePrice: 8499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 28,
        gender: "unisex-adults"
    },
    {
        productId: "disc-blaze-2",
        slug: "disc-blaze-unisex-sneakers-white",
        name:"Disc Blaze - White & Red",
        price:"₹8,499",
        offerPrice:"₹7,649",
        description:"Classic white with red accents",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (4).jpeg",
        basePrice: 8499,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 26,
        gender: "male"
    },
    {
        productId: "lqdcell-1",
        slug: "lqdcell-unisex-sneakers",
        name:"LQDCELL Unisex Sneakers",
        price:"₹10,999",
        offerPrice:"₹8,799",
        description:"Advanced liquid cell technology",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (5).jpeg",
        basePrice: 10999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 22,
        gender: "unisex-adults"
    },
    {
        productId: "lqdcell-2",
        slug: "lqdcell-unisex-sneakers-silver",
        name:"LQDCELL - Silver & Black",
        price:"₹10,999",
        offerPrice:"₹9,899",
        description:"Futuristic silver design",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (6).jpeg",
        basePrice: 10999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 20,
        gender: "male"
    },
    {
        productId: "kids-smash-1",
        slug: "kids-smash-sneakers",
        name:"Kids Smash Sneakers",
        price:"₹4,499",
        offerPrice:"₹3,599",
        description:"Durable kids sneakers",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers2.jpeg",
        basePrice: 4499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 44,
        gender: "boys"
    },
    {
        productId: "kids-smash-2",
        slug: "kids-smash-sneakers-red",
        name:"Kids Smash - Red & Blue",
        price:"₹4,499",
        offerPrice:"₹4,049",
        description:"Colorful red and blue for kids",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers.jpeg",
        basePrice: 4499,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 42,
        gender: "boys"
    },
    {
        productId: "hybrid-rocket-1",
        slug: "hybrid-rocket-unisex-sneakers",
        name:"Hybrid Rocket Unisex Sneakers",
        price:"₹9,499",
        offerPrice:"₹7,599",
        description:"Hybrid performance design",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (7).jpeg",
        basePrice: 9499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 27,
        gender: "unisex-adults"
    },
    {
        productId: "hybrid-rocket-2",
        slug: "hybrid-rocket-unisex-sneakers-orange",
        name:"Hybrid Rocket - Orange & Black",
        price:"₹9,499",
        offerPrice:"₹8,549",
        description:"Bold orange with black",
        img:"/Images/Products/cards/MagMax-NITRO™-Men's-Running-Shoes (8).jpeg",
        basePrice: 9499,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 25,
        gender: "male"
    },
    {
        productId: "wicked-1",
        slug: "wicked-womens-sneakers",
        name:"Wicked Women's Sneakers",
        price:"₹7,999",
        offerPrice:"₹6,399",
        description:"Edgy design for women",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (4).jpeg",
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 30,
        gender: "female"
    },
    {
        productId: "wicked-2",
        slug: "wicked-womens-sneakers-black",
        name:"Wicked - Black & Gold",
        price:"₹7,999",
        offerPrice:"₹7,199",
        description:"Sophisticated black with gold",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (3).jpeg",
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 28,
        gender: "female"
    },
    {
        productId: "mirage-sport-1",
        slug: "mirage-sport-unisex-sneakers",
        name:"Mirage Sport Unisex Sneakers",
        price:"₹8,999",
        offerPrice:"₹7,199",
        description:"Sporty casual sneakers",
        img:"/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers.jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 29,
        gender: "unisex-adults"
    },
    {
        productId: "mirage-sport-2",
        slug: "mirage-sport-unisex-sneakers-blue",
        name:"Mirage Sport - Blue & White",
        price:"₹8,999",
        offerPrice:"₹8,099",
        description:"Fresh blue and white design",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (1).jpeg",
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 27,
        gender: "unisex-adults"
    },
    {
        productId: "kids-velocity-1",
        slug: "kids-velocity-sneakers",
        name:"Kids Velocity Sneakers",
        price:"₹5,499",
        offerPrice:"₹4,399",
        description:"Fast-paced design for active kids",
        img:"/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (8).jpeg",
        basePrice: 5499,
        discountType: "PERCENT",
        discountValue: 20,
        stock: 41,
        gender: "unisex-kids"
    },
    {
        productId: "kids-velocity-2",
        slug: "kids-velocity-sneakers-green",
        name:"Kids Velocity - Green & Yellow",
        price:"₹5,499",
        offerPrice:"₹4,949",
        description:"Energetic green and yellow",
        img:"/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (2).jpeg",
        basePrice: 5499,
        discountType: "PERCENT",
        discountValue: 10,
        stock: 39,
        gender: "boys"
    },
]