const fs = require('fs');
const path = require('path');

// All available local images (these actually exist in public/Images/Products/cards/)
const localImages = {
    blktop1: "/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers (1).jpeg",
    blktop2: "/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers (2).jpeg",
    blktop3: "/Images/Products/cards/Blktop-Rider-Neo-Vintage-Unisex-Sneakers.jpeg",
    easy3: "/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (3).jpeg",
    easy4: "/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (4).jpeg",
    easy5: "/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (5).jpeg",
    easy6: "/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (6).jpeg",
    easy7: "/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (7).jpeg",
    easy8: "/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers (8).jpeg",
    easy2: "/Images/Products/cards/Easy-Rider-Leather-Unisex-Sneakers2.jpeg",
    mesh1: "/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (1).jpeg",
    mesh2: "/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (2).jpeg",
    mesh3: "/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (3).jpeg",
    mesh4: "/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers (4).jpeg",
    mesh5: "/Images/Products/cards/Easy-Rider-Mesh-Unisex-Sneakers.jpeg",
    soft2: "/Images/Products/cards/Softride-Pro-Coast-Res-Unisex-Running-Shoes (2).jpeg",
    soft3: "/Images/Products/cards/Softride-Pro-Coast-Res-Unisex-Running-Shoes (3).jpeg",
};

// Get all local image paths as array
const allLocalImages = Object.values(localImages);

function pickImages(count, startIdx) {
    const result = [];
    for (let i = 0; i < count; i++) {
        result.push(allLocalImages[(startIdx + i) % allLocalImages.length]);
    }
    return result;
}

function generateSizes() {
    return [
        { size: "UK 5", stock: Math.floor(Math.random() * 10) + 1 },
        { size: "UK 6", stock: Math.floor(Math.random() * 10) + 1 },
        { size: "UK 7", stock: Math.floor(Math.random() * 15) + 1 },
        { size: "UK 8", stock: Math.floor(Math.random() * 15) + 1 },
        { size: "UK 9", stock: Math.floor(Math.random() * 10) + 1 },
        { size: "UK 10", stock: Math.floor(Math.random() * 5) + 1 }
    ];
}

function generateKidsSizes() {
    return [
        { size: "UK 1", stock: Math.floor(Math.random() * 10) + 1 },
        { size: "UK 2", stock: Math.floor(Math.random() * 10) + 1 },
        { size: "UK 3", stock: Math.floor(Math.random() * 15) + 1 },
        { size: "UK 4", stock: Math.floor(Math.random() * 10) + 1 },
        { size: "UK 5", stock: Math.floor(Math.random() * 8) + 1 }
    ];
}

const colorNames = [
    { name: "PUMA Black-Frosted Ivory", code: "#000000" },
    { name: "PUMA White-Electric Peppermint", code: "#FFFFFF" },
    { name: "Warm White-Mauved Out", code: "#FDF5E6" },
    { name: "PUMA Navy-Bluemazing", code: "#000080" },
    { name: "For All Time Red", code: "#FF0000" },
    { name: "Vine-PUMA Green", code: "#228B22" },
    { name: "Rose Dust-PUMA White", code: "#D4A5A5" },
    { name: "Vibrant Orange-PUMA White", code: "#FF6600" }
];

function generateColors(count) {
    const shuffled = [...colorNames].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count).map(c => ({
        colorName: c.name,
        colorCode: c.code
    }));
}

const explicitProducts = [
    // ===========================
    // ===== MEN (10 items) =====
    // ===========================
    {
        productId: "fade-pro-1",
        slug: "fade-pro-running-shoes",
        name: "Fade Pro Running Shoes",
        price: "₹7,999",
        offerPrice: "₹3,599",
        description: "Hit new strides in the Darter Pro. Instant cushioning and a lightweight, breathable engineered mesh upper deliver an energised run. Designed for performance, the internal midfoot structure locks you in and a plush tongue keeps you comfortable.",
        img: localImages.easy3,
        images: [localImages.easy3, localImages.easy4, localImages.easy5, localImages.easy6],
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 55,
        stock: 25,
        gender: "male",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA Navy-Bluemazing",
        styleNumber: "310476_01"
    },
    {
        productId: "conduct-pro-1",
        slug: "conduct-pro-running-shoes",
        name: "Conduct Pro Running Shoes",
        price: "₹6,999",
        offerPrice: "₹3,499",
        description: "Conduct Pro combines a PROFOAM midsole with a PROPLATE TPU plate in the heel for superior cushioning and heel stability. Bootie construction for a snug fit with breathable mesh upper.",
        img: localImages.blktop1,
        images: [localImages.blktop1, localImages.blktop2, localImages.blktop3, localImages.easy7],
        basePrice: 6999,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 15,
        gender: "male",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA Black-Asphalt",
        styleNumber: "379438_18"
    },
    {
        productId: "fade-pro-2",
        slug: "fade-pro-running-shoes-white",
        name: "Fade Pro Running Shoes White",
        price: "₹7,999",
        offerPrice: "₹3,599",
        description: "Hit new strides in the Darter Pro. Instant cushioning and a lightweight, breathable engineered mesh upper deliver an energised run.",
        img: localImages.easy8,
        images: [localImages.easy8, localImages.easy2, localImages.easy3, localImages.easy4],
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 55,
        stock: 20,
        gender: "male",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA White-Electric Peppermint",
        styleNumber: "310476_02"
    },
    {
        productId: "conduct-pro-2",
        slug: "conduct-pro-running-shoes-silver",
        name: "Conduct Pro Running Shoes Silver",
        price: "₹6,999",
        offerPrice: "₹3,499",
        description: "Conduct Pro combines a PROFOAM midsole with a PROPLATE TPU plate in the heel for a shoe that offers superior cushioning and heel stability.",
        img: localImages.soft2,
        images: [localImages.soft2, localImages.soft3, localImages.mesh1, localImages.mesh2],
        basePrice: 6999,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 30,
        gender: "male",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA White-PUMA Silver",
        styleNumber: "379438_22"
    },
    {
        productId: "rs-x-toys",
        slug: "rs-x-toys-sneakers",
        name: "RS-X Toys Sneakers",
        price: "₹8,999",
        offerPrice: "₹4,499",
        description: "Based on PUMA's innovative Running System technology, the RS-X line draws its design inspiration from the decade that had the best toys ever: the 1980s.",
        img: localImages.mesh5,
        images: [localImages.mesh5, localImages.mesh1, localImages.mesh2, localImages.mesh3],
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 12,
        gender: "male",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA Black-Blue Atoll",
        styleNumber: "369449_29"
    },
    {
        productId: "suede-classic-men",
        slug: "suede-classic-mens-sneakers",
        name: "Suede Classic Men's Sneakers",
        price: "₹6,499",
        offerPrice: "₹3,899",
        description: "The Suede hit the scene in 1968 and has been changing the game ever since. It's been worn by icons of every generation, from the streets to the stages.",
        img: localImages.easy5,
        images: [localImages.easy5, localImages.easy6, localImages.easy7, localImages.easy8],
        basePrice: 6499,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 28,
        gender: "male",
        sizes: generateSizes(),
        colors: generateColors(3),
        color: "PUMA Black-PUMA White",
        styleNumber: "374915_01"
    },
    {
        productId: "ca-pro-classic-men",
        slug: "ca-pro-classic-mens-sneakers",
        name: "CA Pro Classic Men's Sneakers",
        price: "₹7,999",
        offerPrice: "₹4,799",
        description: "The CA Pro is a California sneaker with a retro-inspired design. Premium leather upper with classic PUMA branding and a comfortable rubber cupsole.",
        img: localImages.blktop2,
        images: [localImages.blktop2, localImages.blktop3, localImages.blktop1, localImages.easy2],
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 22,
        gender: "male",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA White-Vapor Gray",
        styleNumber: "380190_01"
    },
    {
        productId: "smash-v2-men",
        slug: "smash-v2-mens-sneakers",
        name: "Smash V2 Men's Sneakers",
        price: "₹4,499",
        offerPrice: "₹2,699",
        description: "Inspired by classic tennis, the Smash v2 features a clean, streamlined silhouette with a leather upper and signature PUMA Formstrip.",
        img: localImages.easy2,
        images: [localImages.easy2, localImages.easy3, localImages.easy4, localImages.easy5],
        basePrice: 4499,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 40,
        gender: "male",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA White-PUMA Black",
        styleNumber: "365215_07"
    },
    {
        productId: "softride-enzo-men",
        slug: "softride-enzo-evo-mens-running-shoes",
        name: "Softride Enzo Evo Men's Running Shoes",
        price: "₹5,999",
        offerPrice: "₹2,999",
        description: "The Softride Enzo Evo delivers ultra-soft cushioning with the SOFTRIDE midsole technology. Breathable mesh upper with a modern, athletic look.",
        img: localImages.soft3,
        images: [localImages.soft3, localImages.soft2, localImages.mesh3, localImages.mesh4],
        basePrice: 5999,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 35,
        gender: "male",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA Black-PUMA White",
        styleNumber: "377048_01"
    },
    {
        productId: "flyer-runner-men",
        slug: "flyer-runner-mens-running-shoes",
        name: "Flyer Runner Men's Running Shoes",
        price: "₹3,999",
        offerPrice: "₹1,999",
        description: "The Flyer Runner is a lightweight, breathable running shoe that provides comfort and support for your everyday run. SoftFoam+ insole for step-in comfort.",
        img: localImages.mesh4,
        images: [localImages.mesh4, localImages.mesh5, localImages.mesh1, localImages.mesh2],
        basePrice: 3999,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 50,
        gender: "male",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA Black-PUMA White",
        styleNumber: "192257_41"
    },

    // =============================
    // ===== WOMEN (10 items) =====
    // =============================
    {
        productId: "galaxis-pro-womens",
        slug: "galaxis-pro-womens-running-shoes",
        name: "Galaxis Pro Women's Running Shoes",
        price: "₹6,499",
        offerPrice: "₹3,249",
        description: "The Galaxis Pro running shoes are engineered for the everyday runner. With a breathable mesh upper and a plush midsole, these shoes provide maximum comfort.",
        img: localImages.mesh1,
        images: [localImages.mesh1, localImages.mesh2, localImages.mesh3, localImages.mesh4],
        basePrice: 6499,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 45,
        gender: "female",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "Rose Dust-PUMA White",
        styleNumber: "311839_02"
    },
    {
        productId: "mayze-classic-womens",
        slug: "mayze-classic-womens-sneakers",
        name: "Mayze Classic Women's Sneakers",
        price: "₹7,999",
        offerPrice: "₹4,799",
        description: "Step into the spotlight. The Mayze Classic features a stacked sole and contrasting rubber tooling for an edgy, layered look.",
        img: localImages.easy6,
        images: [localImages.easy6, localImages.easy7, localImages.easy8, localImages.easy2],
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 35,
        gender: "female",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA White-PUMA Black",
        styleNumber: "384209_02"
    },
    {
        productId: "blktop-rider-vibrant",
        slug: "blktop-rider-vibrant-womens-sneakers",
        name: "Blktop Rider Vibrant Women's Sneakers",
        price: "₹8,999",
        offerPrice: "₹4,499",
        description: "The Blktop Rider Vibrant brings a colorful update to our iconic Rider franchise, featuring a mesh base with suede and synthetic overlays.",
        img: localImages.blktop3,
        images: [localImages.blktop3, localImages.blktop1, localImages.blktop2, localImages.mesh5],
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 18,
        gender: "female",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "Vibrant Orange-PUMA White",
        styleNumber: "397321_05"
    },
    {
        productId: "mayze-leather-womens",
        slug: "mayze-leather-womens-sneakers",
        name: "Mayze Leather Women's Sneakers",
        price: "₹7,999",
        offerPrice: "₹4,799",
        description: "The Mayze Leather takes design elements from the urban environment and injects them with extra attitude. Eye-catching leather upper with contrasting synthetic details.",
        img: localImages.easy7,
        images: [localImages.easy7, localImages.easy8, localImages.easy2, localImages.easy3],
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 22,
        gender: "female",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA White-PUMA Black",
        styleNumber: "381983_01"
    },
    {
        productId: "rs-x-soft-womens",
        slug: "rs-x-soft-womens-sneakers",
        name: "RS-X Soft Women's Sneakers",
        price: "₹8,999",
        offerPrice: "₹4,499",
        description: "RS-X is back. The future-retro silhouette returns with a soft, feminine touch. Mesh upper with suede overlays and soft pastel colors.",
        img: localImages.mesh3,
        images: [localImages.mesh3, localImages.mesh4, localImages.mesh5, localImages.mesh1],
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 14,
        gender: "female",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "Warm White-Mauved Out",
        styleNumber: "393772_09"
    },
    {
        productId: "cali-star-womens",
        slug: "cali-star-womens-sneakers",
        name: "Cali Star Women's Sneakers",
        price: "₹6,999",
        offerPrice: "₹4,199",
        description: "The Cali Star takes the iconic Cali silhouette and adds a star-perforated twist. Premium leather upper with a chunky rubber outsole for all-day style.",
        img: localImages.easy4,
        images: [localImages.easy4, localImages.easy5, localImages.easy6, localImages.easy7],
        basePrice: 6999,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 30,
        gender: "female",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA White-PUMA White",
        styleNumber: "380176_02"
    },
    {
        productId: "nova-surv-womens",
        slug: "nova-surv-womens-sneakers",
        name: "Nova Surv Women's Sneakers",
        price: "₹7,499",
        offerPrice: "₹3,749",
        description: "A bold sneaker for bold women. The Nova Surv features a chunky platform sole, mesh upper, and eye-catching colorway for maximum street style impact.",
        img: localImages.soft2,
        images: [localImages.soft2, localImages.soft3, localImages.blktop1, localImages.blktop2],
        basePrice: 7499,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 20,
        gender: "female",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA Black-Rose Dust",
        styleNumber: "383203_01"
    },
    {
        productId: "softride-ruby-womens",
        slug: "softride-ruby-womens-running-shoes",
        name: "Softride Ruby Women's Running Shoes",
        price: "₹5,499",
        offerPrice: "₹2,749",
        description: "The Softride Ruby offers ultra-plush cushioning with the SOFTRIDE midsole. Slip-on design with a breathable knit upper for effortless comfort.",
        img: localImages.soft3,
        images: [localImages.soft3, localImages.soft2, localImages.mesh2, localImages.mesh3],
        basePrice: 5499,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 25,
        gender: "female",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA Black-Rose Gold",
        styleNumber: "377050_01"
    },
    {
        productId: "suede-bow-womens",
        slug: "suede-bow-womens-sneakers",
        name: "Suede Bow Women's Sneakers",
        price: "₹6,499",
        offerPrice: "₹3,899",
        description: "The classic Suede gets a feminine upgrade with a statement bow detail. Soft suede upper with satin laces and a rubber outsole.",
        img: localImages.easy8,
        images: [localImages.easy8, localImages.easy2, localImages.easy3, localImages.easy4],
        basePrice: 6499,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 18,
        gender: "female",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "Marshmallow-PUMA White",
        styleNumber: "367317_04"
    },
    {
        productId: "fuse-training-womens",
        slug: "fuse-training-womens-shoes",
        name: "Fuse Training Women's Shoes",
        price: "₹5,999",
        offerPrice: "₹2,999",
        description: "Built for versatile training sessions. The Fuse features a low-profile design with a wide platform for stability and breathable mesh for cool comfort.",
        img: localImages.mesh2,
        images: [localImages.mesh2, localImages.mesh3, localImages.mesh4, localImages.mesh5],
        basePrice: 5999,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 27,
        gender: "female",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA White-Sunblaze",
        styleNumber: "194419_01"
    },

    // ============================
    // ===== KIDS (10 items) =====
    // ============================
    {
        productId: "smash-v2-kids",
        slug: "smash-v2-kids-sneakers",
        name: "Smash V2 Kids Sneakers",
        price: "₹2,999",
        offerPrice: "₹1,799",
        description: "A mini version of the iconic Smash v2, designed for active kids. Synthetic leather upper with a hook-and-loop strap for easy on and off.",
        img: localImages.easy3,
        images: [localImages.easy3, localImages.easy4, localImages.easy5, localImages.easy6],
        basePrice: 2999,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 50,
        gender: "unisex-kids",
        sizes: generateKidsSizes(),
        colors: generateColors(2),
        color: "PUMA White-PUMA Black",
        styleNumber: "365184_28"
    },
    {
        productId: "fun-racer-kids",
        slug: "fun-racer-kids-running-shoes",
        name: "Fun Racer Kids Running Shoes",
        price: "₹2,499",
        offerPrice: "₹1,499",
        description: "Lightweight and fun! The Fun Racer is perfect for little runners, featuring a breathable mesh upper and a flexible outsole for natural movement.",
        img: localImages.mesh5,
        images: [localImages.mesh5, localImages.mesh1, localImages.mesh2, localImages.mesh3],
        basePrice: 2499,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 40,
        gender: "unisex-kids",
        sizes: generateKidsSizes(),
        colors: generateColors(2),
        color: "PUMA Black-High Risk Red",
        styleNumber: "192971_11"
    },
    {
        productId: "flyer-runner-kids",
        slug: "flyer-runner-kids-shoes",
        name: "Flyer Runner Kids Shoes",
        price: "₹2,799",
        offerPrice: "₹1,399",
        description: "The Flyer Runner for kids provides a lightweight, breathable fit with a SoftFoam+ insole for incredible step-in comfort. Hook-and-loop closure for easy wear.",
        img: localImages.blktop1,
        images: [localImages.blktop1, localImages.blktop2, localImages.blktop3, localImages.easy7],
        basePrice: 2799,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 35,
        gender: "unisex-kids",
        sizes: generateKidsSizes(),
        colors: generateColors(2),
        color: "PUMA Navy-Bluemazing",
        styleNumber: "192928_36"
    },
    {
        productId: "suede-classic-kids",
        slug: "suede-classic-kids-sneakers",
        name: "Suede Classic Kids Sneakers",
        price: "₹3,499",
        offerPrice: "₹2,099",
        description: "The timeless Suede Classic, sized down for kids. Premium suede upper with the iconic PUMA Formstrip. Rubber outsole for durable traction.",
        img: localImages.easy5,
        images: [localImages.easy5, localImages.easy6, localImages.easy7, localImages.easy8],
        basePrice: 3499,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 30,
        gender: "unisex-kids",
        sizes: generateKidsSizes(),
        colors: generateColors(3),
        color: "Peacoat-PUMA White",
        styleNumber: "380563_03"
    },
    {
        productId: "rs-x-kids",
        slug: "rs-x-kids-sneakers",
        name: "RS-X Kids Sneakers",
        price: "₹4,999",
        offerPrice: "₹2,999",
        description: "Future-retro style for the next generation. The RS-X Kids features bold colors, a chunky silhouette, and a comfortable cushioned midsole.",
        img: localImages.blktop2,
        images: [localImages.blktop2, localImages.blktop3, localImages.blktop1, localImages.easy2],
        basePrice: 4999,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 25,
        gender: "unisex-kids",
        sizes: generateKidsSizes(),
        colors: generateColors(2),
        color: "PUMA White-High Risk Red",
        styleNumber: "374921_01"
    },
    {
        productId: "caven-kids-white",
        slug: "caven-kids-white-sneakers",
        name: "Caven Kids White Sneakers",
        price: "₹2,999",
        offerPrice: "₹1,799",
        description: "Classic court-style sneaker for kids. Clean white leather upper with PUMA branding and a durable rubber outsole. Perfect for school and play.",
        img: localImages.easy2,
        images: [localImages.easy2, localImages.easy3, localImages.easy4, localImages.easy5],
        basePrice: 2999,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 45,
        gender: "unisex-kids",
        sizes: generateKidsSizes(),
        colors: generateColors(2),
        color: "PUMA White-Island Green",
        styleNumber: "382057_07"
    },
    {
        productId: "anzarun-lite-kids",
        slug: "anzarun-lite-kids-sneakers",
        name: "Anzarun Lite Kids Sneakers",
        price: "₹2,499",
        offerPrice: "₹1,499",
        description: "A lightweight, sporty sneaker for kids on the go. Features a breathable mesh upper, SoftFoam+ insole, and a hook-and-loop closure for easy wear.",
        img: localImages.mesh4,
        images: [localImages.mesh4, localImages.mesh5, localImages.mesh1, localImages.mesh2],
        basePrice: 2499,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 38,
        gender: "unisex-kids",
        sizes: generateKidsSizes(),
        colors: generateColors(2),
        color: "PUMA Black-High Risk Red",
        styleNumber: "372009_24"
    },
    {
        productId: "rebound-joy-kids",
        slug: "rebound-joy-kids-sneakers",
        name: "Rebound Joy Kids Sneakers",
        price: "₹3,499",
        offerPrice: "₹2,099",
        description: "Inspired by basketball heritage, the Rebound Joy offers a high-top silhouette with a padded collar and tongue for comfort. Durable synthetic upper.",
        img: localImages.soft2,
        images: [localImages.soft2, localImages.soft3, localImages.blktop1, localImages.blktop2],
        basePrice: 3499,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 28,
        gender: "unisex-kids",
        sizes: generateKidsSizes(),
        colors: generateColors(2),
        color: "PUMA White-Peacoat",
        styleNumber: "381985_12"
    },
    {
        productId: "x-ray-speed-kids",
        slug: "x-ray-speed-kids-sneakers",
        name: "X-Ray Speed Kids Sneakers",
        price: "₹3,999",
        offerPrice: "₹2,399",
        description: "The X-Ray Speed for kids combines a layered mesh and synthetic upper with bold color blocking. Lightweight EVA midsole for cushioned comfort.",
        img: localImages.blktop3,
        images: [localImages.blktop3, localImages.blktop1, localImages.blktop2, localImages.mesh5],
        basePrice: 3999,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 22,
        gender: "unisex-kids",
        sizes: generateKidsSizes(),
        colors: generateColors(3),
        color: "PUMA White-High Risk Red-Gray",
        styleNumber: "384898_14"
    },
    {
        productId: "softride-kids",
        slug: "softride-one4all-kids-running-shoes",
        name: "Softride One4All Kids Running Shoes",
        price: "₹3,499",
        offerPrice: "₹1,749",
        description: "Ultra-soft SOFTRIDE cushioning technology sized for kids. Slip-on design with elastic laces and a soft mesh upper. Perfect for active play and sports.",
        img: localImages.soft3,
        images: [localImages.soft3, localImages.soft2, localImages.mesh3, localImages.mesh4],
        basePrice: 3499,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 32,
        gender: "unisex-kids",
        sizes: generateKidsSizes(),
        colors: generateColors(2),
        color: "PUMA Black-PUMA White",
        styleNumber: "378241_04"
    },

    // ================================
    // ===== UNISEX (5 items) =========
    // ================================
    {
        productId: "easy-rider-unisex",
        slug: "easy-rider-leather-unisex-sneakers",
        name: "Easy Rider Leather Unisex Sneakers",
        price: "₹6,999",
        offerPrice: "₹4,199",
        description: "A heritage running shoe reimagined for the streets. The Easy Rider features a premium suede and leather upper with the iconic T-toe detail.",
        img: localImages.easy3,
        images: [localImages.easy3, localImages.easy4, localImages.easy5, localImages.easy6],
        basePrice: 6999,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 30,
        gender: "unisex-adults",
        sizes: generateSizes(),
        colors: generateColors(3),
        color: "PUMA Navy-Frosted Ivory",
        styleNumber: "387617_01"
    },
    {
        productId: "blktop-rider-unisex",
        slug: "blktop-rider-neo-vintage-unisex-sneakers",
        name: "Blktop Rider Neo Vintage Unisex Sneakers",
        price: "₹7,999",
        offerPrice: "₹3,999",
        description: "The Blktop Rider delivers a retro-inspired look with modern comfort. Mesh and suede upper with a cushioned midsole for all-day wear.",
        img: localImages.blktop1,
        images: [localImages.blktop1, localImages.blktop2, localImages.blktop3, localImages.mesh1],
        basePrice: 7999,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 20,
        gender: "unisex-adults",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "Warm White-Mauved Out",
        styleNumber: "393764_02"
    },
    {
        productId: "magmax-nitro-unisex",
        slug: "magmax-nitro-unisex-running-shoes",
        name: "MagMax NITRO Unisex Running Shoes",
        price: "₹8,999",
        offerPrice: "₹4,499",
        description: "Featuring PUMA's NITRO foam technology for responsive cushioning and lightweight energy return. Engineered mesh upper with a supportive midfoot cage.",
        img: localImages.mesh1,
        images: [localImages.mesh1, localImages.mesh2, localImages.mesh3, localImages.mesh4],
        basePrice: 8999,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 18,
        gender: "unisex-adults",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA Black-Sunblaze",
        styleNumber: "377028_01"
    },
    {
        productId: "softride-coast-unisex",
        slug: "softride-pro-coast-unisex-running-shoes",
        name: "Softride Pro Coast Unisex Running Shoes",
        price: "₹5,999",
        offerPrice: "₹2,999",
        description: "Ultra-soft SOFTRIDE cushioning meets a sleek silhouette. The Pro Coast features a breathable mesh upper and a durable rubber outsole.",
        img: localImages.soft2,
        images: [localImages.soft2, localImages.soft3, localImages.mesh2, localImages.mesh3],
        basePrice: 5999,
        discountType: "PERCENT",
        discountValue: 50,
        stock: 25,
        gender: "unisex-adults",
        sizes: generateSizes(),
        colors: generateColors(2),
        color: "PUMA White-Cool Light Gray",
        styleNumber: "377013_07"
    },
    {
        productId: "easy-rider-mesh-unisex",
        slug: "easy-rider-mesh-unisex-sneakers",
        name: "Easy Rider Mesh Unisex Sneakers",
        price: "₹5,999",
        offerPrice: "₹3,599",
        description: "A breathable mesh take on the Easy Rider classic. Lightweight and airy, perfect for warm-weather styling with heritage PUMA design.",
        img: localImages.mesh5,
        images: [localImages.mesh5, localImages.mesh1, localImages.mesh4, localImages.easy7],
        basePrice: 5999,
        discountType: "PERCENT",
        discountValue: 40,
        stock: 22,
        gender: "unisex-adults",
        sizes: generateSizes(),
        colors: generateColors(3),
        color: "For All Time Red-PUMA White",
        styleNumber: "387617_05"
    }
];

const content = `export const CardDatas = ${JSON.stringify(explicitProducts, null, 4)};\n`;

fs.writeFileSync(path.join(__dirname, 'src', 'constant', 'Products', 'Cards.js'), content);
console.log(`Successfully generated Cards.js with ${explicitProducts.length} products (Men: 10, Women: 10, Kids: 10, Unisex: 5).`);
