/**
 * Bonus items data
 * Small accessories and shoe-related items that can be added as bonus items
 */

export const bonusItems = [
  {
    id: "bonus-socks-1",
    productId: "puma-athletic-socks-pack",
    name: "PUMA Athletic Socks Pack (3 Pairs)",
    price: "₹599",
    offerPrice: "₹399",
    basePrice: 599,
    discountType: "PERCENT",
    discountValue: 33,
    image: "https://plus.unsplash.com/premium_photo-1723223095958-612c6ffb1d82?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Comfortable athletic socks perfect for running",
    stock: 50,
    size: "One Size",
    category: "Accessories",
  },
  {
    id: "bonus-socks-2",
    productId: "puma-cushioned-socks",
    name: "PUMA Cushioned Performance Socks",
    price: "₹499",
    basePrice: 499,
    discountType: null,
    discountValue: 0,
    image: "https://images.unsplash.com/photo-1640026199235-c24aa417b552?q=80&w=765&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Extra cushioning for maximum comfort",
    stock: 30,
    size: "One Size",
    category: "Accessories",
  },
  {
    id: "bonus-socks-3",
    productId: "puma-no-show-socks",
    name: "PUMA No-Show Socks (3 Pairs)",
    price: "₹449",
    offerPrice: "₹349",
    basePrice: 449,
    discountType: "PERCENT",
    discountValue: 22,
    image: "https://images.unsplash.com/photo-1730447153639-f559d50a91ec?q=80&w=736&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Invisible comfort for your favorite sneakers",
    stock: 45,
    size: "One Size",
    category: "Accessories",
  },
  {
    id: "bonus-socks-4",
    productId: "puma-ankle-socks",
    name: "PUMA Ankle Socks Pack (5 Pairs)",
    price: "₹699",
    offerPrice: "₹549",
    basePrice: 699,
    discountType: "PERCENT",
    discountValue: 21,
    image: "https://images.unsplash.com/photo-1632944968588-3ec2870641ce?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Perfect fit for everyday wear",
    stock: 60,
    size: "One Size",
    category: "Accessories",
  },
  {
    id: "bonus-socks-5",
    productId: "puma-crew-socks",
    name: "PUMA Crew Socks (2 Pairs)",
    price: "₹399",
    basePrice: 399,
    discountType: null,
    discountValue: 0,
    image: "https://plus.unsplash.com/premium_photo-1723223095958-612c6ffb1d82?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Classic crew length for maximum coverage",
    stock: 35,
    size: "One Size",
    category: "Accessories",
  },
  {
    id: "bonus-socks-6",
    productId: "puma-sport-socks",
    name: "PUMA Sport Socks Pack (4 Pairs)",
    price: "₹799",
    offerPrice: "₹599",
    basePrice: 799,
    discountType: "PERCENT",
    discountValue: 25,
    image: "https://images.unsplash.com/photo-1640026199235-c24aa417b552?q=80&w=765&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "High-performance socks for active lifestyle",
    stock: 40,
    size: "One Size",
    category: "Accessories",
  },
];

